query states($page: Int, $search: String, $limit: Int, $sort: String) {
	states(page: $page, search: $search, limit: $limit, sort: $sort) {
		count
		page
		pageSize
		data {
			id
			name
			value
			code
			img
			imgCdn
			flag
			lang
			sort
			active
			createdAt
			updatedAt
		}
	}
}
